[features]
seeds = false
skip-lint = false
[programs.localnet]
service_marketplace = "EYk41B1oPd5hcTNcx7u2oGykSHHaEq4Uo9i2oYmZvDXb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kristoffer/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./metadata.so"
